---
title: "Washington County Tracts with No HeadStart Location Profile"
author: "Paul Collins"
date: "6/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r code, echo = FALSE}

packages <- c("RColorBrewer","acs", "tidyverse", "tidycensus", "tigris", "leaflet", "mapview", "tmap", "DT", "sf", "gganimate", "report", "ipumsr", "xtable", "kableExtra", "knitr", "RgoogleMaps", "stargazer")

lapply(packages, library, character.only = TRUE)

#### get data for the hawkins school system, kepler elementary school, mcpheters bend, fugate hill classrooms ####

#### load the variable names ####

dp_table_variables_18 <- load_variables(2018, "acs5/profile", cache = TRUE)

new_names_18 <- c("variable", "label", "concept")

names(dp_table_variables_18) <- new_names_18   

#### hawkins school system ####

tnss_dp02_2018 <- get_acs(geography = "school district (unified)", state = "TN", table = "DP02", year = 2018, cache = TRUE)

tnss_dp03_2018 <- get_acs(geography = "school district (unified)", state = "TN", table = "DP03", year = 2018, cache = TRUE)

tnss_dp04_2018 <- get_acs(geography = "school district (unified)", state = "TN", table = "DP04", year = 2018, cache = TRUE)

tnss_dp05_2018 <- get_acs(geography = "school district (unified)", state = "TN", table = "DP05", year = 2018, cache = TRUE)

tnss_dp02_18 <- inner_join(tnss_dp02_2018, dp_table_variables_18, by = "variable")

tnss_dp03_18 <- inner_join(tnss_dp03_2018, dp_table_variables_18, by = "variable")

tnss_dp04_18 <- inner_join(tnss_dp04_2018, dp_table_variables_18, by = "variable")

tnss_dp05_18 <- inner_join(tnss_dp05_2018, dp_table_variables_18, by = "variable")

tn_data_profile_18 <- rbind(tnss_dp02_18, tnss_dp03_18, tnss_dp04_18, tnss_dp05_18)

districts <- school_districts(state = "TN", type = "unified", refresh = TRUE)

districts <- st_as_sf(districts)

### need washington and greene county school districts ###

greene_18 <- districts %>%
  filter(NAME == "Greene County School District")

gchs_dp_18 <- tn_data_profile_18 %>%
  filter(NAME == "Greene County School District, Tennessee")

wash_18 <- districts %>%
  filter(NAME == "Washington County School District")

wchs_dp_18 <- tn_data_profile_18 %>%
  filter(NAME == "Washington County School District, Tennessee")

#### pull washington and Greene census tract data ####

#greene

Greene_dp02_2018 <- get_acs(geography = "tract", county = "Greene", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)

Greene_dp03_2018 <- get_acs(geography = "tract", county = "Greene", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)

Greene_dp04_2018 <- get_acs(geography = "tract", county = "Greene", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)

Greene_dp05_2018 <- get_acs(geography = "tract", county = "Greene", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)    

Greene_dp02_18 <- inner_join(Greene_dp02_2018, dp_table_variables_18, by = "variable")

Greene_dp03_18 <- inner_join(Greene_dp03_2018, dp_table_variables_18, by = "variable")

Greene_dp04_18 <- inner_join(Greene_dp04_2018, dp_table_variables_18, by = "variable")

Greene_dp05_18 <- inner_join(Greene_dp05_2018, dp_table_variables_18, by = "variable")

Greene_data_profile <- rbind(Greene_dp02_18, Greene_dp03_18, Greene_dp04_18, Greene_dp05_18)

#washington

Washington_dp02_2018 <- get_acs(geography = "tract", county = "Washington", state = "TN", table = "DP02", year = 2018, geometry = TRUE, cache = TRUE)

Washington_dp03_2018 <- get_acs(geography = "tract", county = "Washington", state = "TN", table = "DP03", year = 2018, geometry = TRUE, cache = TRUE)

Washington_dp04_2018 <- get_acs(geography = "tract", county = "Washington", state = "TN", table = "DP04", year = 2018, geometry = TRUE, cache = TRUE)

Washington_dp05_2018 <- get_acs(geography = "tract", county = "Washington", state = "TN", table = "DP05", year = 2018, geometry = TRUE, cache = TRUE)    

Washington_dp02_18 <- inner_join(Washington_dp02_2018, dp_table_variables_18, by = "variable")

Washington_dp03_18 <- inner_join(Washington_dp03_2018, dp_table_variables_18, by = "variable")

Washington_dp04_18 <- inner_join(Washington_dp04_2018, dp_table_variables_18, by = "variable")

Washington_dp05_18 <- inner_join(Washington_dp05_2018, dp_table_variables_18, by = "variable")

Washington_data_profile <- rbind(Washington_dp02_18, Washington_dp03_18, Washington_dp04_18, Washington_dp05_18)



### use geoid's because its easier to filter ###

wash_hs_GEOID <- c(47179061901, 47179061402, 47179060900, 47179061100, 47179060100, 47179061602, 47179061902, 47179060800)

chuckey_hs_GEOID <- c(47059090900)

wash_nohs_GEOID <- wash_no_hs_tracts$GEOID

wash_nohs_GEOID

wash_hs_tracts <- Washington_data_profile %>%
  filter(GEOID %in% wash_hs_GEOID)

chuckey_hs_tract <- Greene_data_profile %>%
  filter(GEOID %in% chuckey_hs_GEOID)

wash_no_hs_tracts <- Washington_data_profile %>%
  filter(GEOID %in% wash_nohs_GEOID)


# add the school names to the location data frame #

south_central <- wash_hs_tracts %>%
  filter(GEOID == 47179061901)

school <- rep("South Central", length(south_central$GEOID))

sc <- cbind(school, south_central)

chuckey <- chuckey_hs_tract

school <- rep("Chuckey", length(chuckey$GEOID))

chu <- cbind(school, chuckey)

west_view <- wash_hs_tracts %>%
  filter(GEOID == 47179061901)

school <- rep("West View", length(west_view$GEOID))

wv <- cbind(school, west_view)

boones <- wash_hs_tracts %>%
  filter(GEOID == 47179061402)

school <- rep("Boones Creek", length(boones$GEOID))

bc <- cbind(school, boones)

child <- wash_hs_tracts %>%
  filter(GEOID == 47179060900)

school <- rep("Children First", length(child$GEOID))

cf <- cbind(school, child)

lake <- wash_hs_tracts %>%
  filter(GEOID == 47179061100)

school <- rep("Lake Terrace", length(lake$GEOID))

lt <- cbind(school, lake)

dunbar <- wash_hs_tracts %>%
  filter(GEOID == 47179060100)

school <- rep("Dunbar", length(dunbar$GEOID))

dun <- cbind(school, dunbar)

harmony <- wash_hs_tracts %>%
  filter(GEOID == 47179061602)

school <- rep("Harmony", length(harmony$GEOID))

harm <- cbind(school, harmony)

grandview <- wash_hs_tracts %>%
  filter(GEOID == 47179061902)

school <-rep("Grandview", length(grandview$GEOID))

gv <- cbind(school, grandview)

southside <- wash_hs_tracts %>%
  filter(GEOID == 47179060800)

school <- rep("South Side", length(southside$GEOID))

ss <- cbind(school, southside)

pretty_tracts <- rbind(sc, chu, wv, bc, cf, lt, dun, harm, gv, ss)

View(pretty_tracts)


####pull out the variables we need ####

hs_vars <- c("DP02_0045", "DP02_0046", "DP02_0047", "DP02_0053", "DP02_0071", "DP02_0112", "DP02_0151", "DP02_0152", "DP03_0009", "DP03_0062", "DP03_0072", "DP03_0074", "DP03_0119", "DP03_0121",
             "DP05_0001", "DP05_0005", "DP05_0018", "DP05_0064")

hs_per_vars <- c("DP02_0045P", "DP02_0046P", "DP02_0047P", "DP02_0053P", "DP02_0071P", "DP02_0112P", "DP02_0151P", "DP02_0152P", "DP03_0009P", "DP03_0062P", "DP03_0072P", "DP03_0074P", "DP03_0119P", "DP03_0121P",
                 "DP05_0001P", "DP05_0005P","DP05_0018P", "DP05_0064P")

hs_vars_names <- c("Grandparent living in household and responsible for children under 1", "Grandparent living in household and responsible for children 1-2 years old", "Grandparent living in household and responsible for children 3-4 years olds",
                   "Children enrolled in preschool or nursery school", "Citizens with a Disability", "Population ESL", "Households with a Computer", "Households with Broadband internet", "Unemployment Rate", "Median Income",
                   "Total Households with Cash Public Assistance", "Total Households with SNAP", "Percentage of all families below poverty line", "Percentage of all families below poverty line with children under 5",
                   "Total Population", "Population Age under 5","Median Age", "Population Racially White")


df_tracts <- pretty_tracts %>%
  filter(variable %in% hs_vars)

df_per_tracts <- pretty_tracts %>%
  filter(variable %in% hs_per_vars)

df_combined <- cbind(hs_vars_names, df_tracts, df_per_tracts)

trimmed_df <- df_combined[,c(1,2,4,6,7,14,15)]

###get rid of location for tables 

no_location_trimmed_df <- st_set_geometry(trimmed_df, NULL)

###make new names for table 

hs_table_names <- c("Measure", "Head Start Location", "Census Tract", "Count", "Margin of Error", "Percent", "Percent Margin of Error")

names(no_location_trimmed_df) <- hs_table_names

wash_hs_datatable <- datatable(no_location_trimmed_df, caption = "Various Metrics for Washington County (and Chuckey) Census Tracts Containing a Head Start")

wash_hs_datatable

##pdf table##

xtable(no_location_trimmed_df %>% filter(`Head Start Location`== "South Central"))

###### repeat that for washington county tracts without a head start ####

###make these pretty and see if it helps###

loc1 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179060400)

no_school <- rep("Loc1", length(loc1$GEOID))

l1 <- cbind(no_school, loc1)

loc2 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179060501)

no_school <- rep("Loc1", length(loc2$GEOID))

l2 <- cbind(no_school, loc2)  

loc3 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179060502)

no_school <- rep("Loc3", length(loc3$GEOID))

l3 <- cbind(no_school, loc3)

loc4 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179060600)

no_school <- rep("Loc4", length(loc4$GEOID))

l4 <- cbind(no_school, loc4)

loc5 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179060700)

no_school <- rep("Loc5", length(loc5$GEOID))

l5 <- cbind(no_school, loc5)

loc6 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061000)

no_school <- rep("Loc6", length(loc6$GEOID))

l6 <- cbind(no_school, loc6)

loc7 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061200)

no_school <- rep("Loc7", length(loc7$GEOID))

l7 <- cbind(no_school, loc7)

loc8 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061300)

no_school <- rep("Loc8", length(loc8$GEOID))

l8 <- cbind(no_school, loc8)

loc9 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061401)

no_school <- rep("Loc9", length(loc9$GEOID))

l9 <- cbind(no_school, loc9)

loc10 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061500)

no_school <- rep("Loc10", length(loc10$GEOID))

l10 <- cbind(no_school, loc10)

loc11 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061601)

no_school <- rep("Loc11", length(loc11$GEOID))

l11 <- cbind(no_school, loc11)

loc12 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061701)

no_school <- rep("Loc12", length(loc12$GEOID))

l12 <- cbind(no_school, loc12)

loc13 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061702)

no_school <- rep("Loc13", length(loc13$GEOID))

l13 <- cbind(no_school, loc13)

loc14 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179061800)

no_school <- rep("Loc14", length(loc14$GEOID))

l14 <- cbind(no_school, loc14)

loc15 <- wash_no_hs_tracts %>%
  filter(GEOID == 47179062000)

no_school <- rep("Loc15", length(loc15$GEOID))

l15 <- cbind(no_school, loc15)

nohs_pretty_tracts <- rbind(l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15)

nohs_pretty_tracts


nohs_df_tracts <- nohs_pretty_tracts %>%
  filter(variable %in% hs_vars)

nohs_df_per_tracts <- nohs_pretty_tracts %>%
  filter(variable %in% hs_per_vars)

nohs_df_combined <- cbind(hs_vars_names, nohs_df_tracts, nohs_df_per_tracts)


trimmed_nohs_df <- nohs_df_combined[,c(1,2,4,6,7,14,15)]

###get rid of location for tables 

no_location_trimmed_nohs_df <- st_set_geometry(trimmed_nohs_df, NULL)

### make data table ###

nohs_table_names <- c("Measure", "Census Tract", "Count", "Margin of Error", "Percent", "Percent Margin of Error")

names(no_location_trimmed_nohs_df) <- nohs_table_names

wash_nohs_datatable <- datatable(no_location_trimmed_nohs_df, caption = "Various Metrics for Washington County Census Tracts WITHOUT a Head Start")



### worry about this ^^^ later ##

### test for differences between south central and other head start school tracts ####




```